name: Azure App Services CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: |
            cd api
            mvn clean package
      - uses: azure/webapps-deploy@v2
        with:
          app-name: myhealthnewapi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
          package: '${{ github.workspace }}/api/target/*.jar'
